[package]
name = "hello-rocket-yew-frontend"
version = "0.1.0"
authors = ["Noah Rosenzweig <rosenzweig.noah@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
json    = "0.12.0"
yew     = "0.8.0"
